[profile.default]
fail-fast = false
retries = { backoff = "fixed", count = 1, delay = "2s" }
slow-timeout = { period = "60s", terminate-after = 2 }

[profile.ci]
fail-fast = false
retries = { backoff = "fixed", count = 1, delay = "2s" }
slow-timeout = { period = "90s", terminate-after = 2 }
status-level = "all"
final-status-level = "slow"

[profile.release]
fail-fast = false
retries = { backoff = "fixed", count = 0, delay = "1s" }
slow-timeout = { period = "90s", terminate-after = 2 }
status-level = "all"
final-status-level = "all"
